# Generated by Django 2.2.5 on 2020-02-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddChild', '0002_auto_20200211_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='addchild',
            name='month',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active')], default='pending', max_length=9),
        ),
    ]
