# Generated by Django 2.2.5 on 2020-02-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AddChild', '0003_addchild_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addchild',
            old_name='month',
            new_name='status',
        ),
    ]
