# Generated by Django 2.2.5 on 2020-02-20 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AddChild', '0004_auto_20200217_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='addchild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addchild',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
