# Generated by Django 2.2.5 on 2020-02-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('AddChild', '0005_auto_20200220_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='addchild',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stu_class', to='main_app.Classes'),
        ),
        migrations.AddField(
            model_name='addchild',
            name='institute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studnt_institute', to='main_app.Institute'),
        ),
    ]
