# Generated by Django 2.2.5 on 2020-03-07 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200219_1556'),
        ('AddChild', '0006_auto_20200220_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondryInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_type', models.CharField(choices=[('primary', 'primary'), ('secondry', 'secondry')], default='secondry', max_length=9)),
                ('student_Class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_Class', to='main_app.Classes')),
                ('student_institute', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_institute', to='main_app.Institute')),
                ('student_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_name', to='main_app.UserProfile')),
            ],
        ),
    ]
