# Generated by Django 2.2.5 on 2020-03-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddChild', '0007_secondryinstitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondryinstitute',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('active', 'active')], default='pending', max_length=9),
        ),
    ]
