# Generated by Django 2.2.5 on 2020-03-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AddChild', '0008_secondryinstitute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondryinstitute',
            name='student_rollno',
            field=models.IntegerField(null=True),
        ),
    ]
