# Generated by Django 2.2.7 on 2020-01-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0005_auto_20200116_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='examschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=100, null=True)),
                ('test_type', models.CharField(max_length=100, null=True)),
                ('test_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('test_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('subject_teacher', models.CharField(max_length=100)),
                ('test_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testclass', to='main_app.Classes')),
                ('test_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_class', to='main_app.Subjects')),
            ],
        ),
    ]
