# Generated by Django 2.2.7 on 2020-02-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_result', '0002_auto_20200210_0951'),
        ('examschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_type',
            field=models.CharField(choices=[('Class', 'Class'), ('Unit', 'Unit'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ExamType',
        ),
    ]
