# Generated by Django 2.2.7 on 2020-02-12 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('examschedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='exam_type_id',
        ),
        migrations.AddField(
            model_name='examtype',
            name='exam_max_marks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examtype',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examtype_institute', to='main_app.Institute'),
        ),
    ]
