# Generated by Django 2.2.7 on 2020-02-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='exam_class',
        ),
    ]
