# Generated by Django 2.2.7 on 2020-02-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='exam_time_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examtype',
            name='exam_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
