# Generated by Django 2.2.7 on 2020-06-12 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_subject_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_subject_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
