# Generated by Django 2.2.7 on 2020-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Exam_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_start_date', models.DateField(max_length=100, null=True)),
                ('edit_end_date', models.DateField(max_length=100, null=True)),
            ],
        ),
    ]
