# Generated by Django 2.2.7 on 2020-02-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0002_remove_examtype_exam_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='exam_max_marks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
