# Generated by Django 2.2.7 on 2020-01-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0002_auto_20200120_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='assign_teacher',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='subject_teacher',
        ),
    ]
