# Generated by Django 2.2.7 on 2020-02-10 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0002_auto_20200210_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Class', 'Class'), ('Unit', 'Unit'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_details', to='examschedule.ExamType'),
        ),
    ]
