# Generated by Django 2.2.7 on 2020-07-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200715_1531'),
        ('examschedule', '0002_edit_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_exam_date',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edit_date_institute', to='main_app.Institute'),
        ),
    ]
