# Generated by Django 2.2.7 on 2020-02-04 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0003_examtype_exam_max_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_assign_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_assign_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='exam_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examdetails_class', to='main_app.Classes'),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_type_info', to='examschedule.ExamType'),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examdetails_institute', to='main_app.Institute'),
        ),
    ]
