# Generated by Django 2.2.7 on 2020-01-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200116_1423'),
        ('class_schedule', '0010_merge_20200110_1657'),
        ('examschedule', '0003_auto_20200120_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='assign_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_tecaher', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examschedule', to='main_app.Institute'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_tecaher', to='class_schedule.Schedule'),
        ),
    ]
