# Generated by Django 2.2.7 on 2020-02-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0003_auto_20200210_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='exam_type_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
