# Generated by Django 2.2.7 on 2020-02-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0004_auto_20200212_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='exam_type_sr_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
