# Generated by Django 2.2.7 on 2020-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0004_auto_20200120_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='test_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Middle', 'Middle'), ('Highschool', 'Highschool')], max_length=50, null=True),
        ),
    ]
