# Generated by Django 2.2.7 on 2020-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0005_auto_20200122_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='test_type',
            field=models.CharField(choices=[('Unit', 'Unit'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], max_length=50, null=True),
        ),
    ]
