# Generated by Django 2.2.7 on 2020-02-10 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('examschedule', '0006_remove_examtype_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examtype_institute', to='main_app.Institute'),
        ),
    ]
