# Generated by Django 2.2.7 on 2020-02-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('examschedule', '0006_auto_20200220_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcode',
            name='exam_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examcode_class', to='main_app.Classes'),
        ),
    ]
