# Generated by Django 2.2.7 on 2020-02-20 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('examschedule', '0007_examcode_exam_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcode',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examcode_institute', to='main_app.Institute'),
        ),
    ]
