# Generated by Django 2.2.7 on 2020-01-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0007_examschedule_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='Class',
        ),
    ]
