# Generated by Django 2.2.7 on 2020-02-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0007_examtype_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtype',
            name='institute',
        ),
    ]
