# Generated by Django 2.2.7 on 2020-02-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0008_examcode_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='exam_sr_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examdetails',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_details', to='examschedule.ExamType'),
        ),
        migrations.DeleteModel(
            name='ExamCode',
        ),
    ]
