# Generated by Django 2.2.7 on 2020-01-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0009_auto_20200123_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examschedule',
            old_name='test_class',
            new_name='Class',
        ),
    ]
