# Generated by Django 2.2.7 on 2020-01-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0010_auto_20200123_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examschedule',
            name='test_code',
        ),
    ]
