# Generated by Django 2.2.7 on 2020-01-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0011_remove_examschedule_test_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examschedule',
            old_name='Class',
            new_name='test_class',
        ),
    ]
