# Generated by Django 2.2.7 on 2020-01-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0012_auto_20200124_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='test_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
