# Generated by Django 2.2.7 on 2020-01-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0013_examschedule_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='test_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_subject', to='main_app.Subjects'),
        ),
    ]
