# Generated by Django 2.2.7 on 2020-01-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0014_auto_20200124_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='assign_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_tecaher', to='class_schedule.Schedule'),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_tecaher', to='class_schedule.Schedule'),
        ),
    ]
