# Generated by Django 2.2.7 on 2020-01-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0015_auto_20200124_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='test_date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='test_time',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
