# Generated by Django 2.2.7 on 2020-01-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200116_1423'),
        ('class_schedule', '0010_merge_20200110_1657'),
        ('examschedule', '0016_auto_20200124_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examschedule',
            old_name='test_date',
            new_name='test_date_five',
        ),
        migrations.RenameField(
            model_name='examschedule',
            old_name='test_time',
            new_name='test_time_five',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='assign_teacher',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='subject_teacher',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='test_subject',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='assign_teacher_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_five', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='assign_teacher_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_four', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='assign_teacher_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_one', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='assign_teacher_six',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_six', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='assign_teacher_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_three', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='assign_teacher_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_two', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject_teacher_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_five', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject_teacher_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_four', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject_teacher_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_one', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject_teacher_six',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_six', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject_teacher_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_three', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='subject_teacher_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_two', to='class_schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_date_four',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_date_one',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_date_six',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_date_three',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_date_two',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_subject_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_subject_five', to='main_app.Subjects'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_subject_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_subject_four', to='main_app.Subjects'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_subject_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_subject_one', to='main_app.Subjects'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_subject_six',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_subject_six', to='main_app.Subjects'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_subject_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_subject_three', to='main_app.Subjects'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_subject_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_subject_two', to='main_app.Subjects'),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_time_four',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_time_one',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_time_six',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_time_three',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examschedule',
            name='test_time_two',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
