# Generated by Django 2.2.7 on 2020-01-25 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0018_auto_20200124_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examschedule',
            name='assign_teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='assign_teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='assign_teacher3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_three', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='assign_teacher4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_four', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='assign_teacher5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_five', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='assign_teacher6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_teacher_six', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject_teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject_teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject_teacher3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_three', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject_teacher4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_four', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject_teacher5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_five', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examschedule',
            name='subject_teacher6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_six', to=settings.AUTH_USER_MODEL),
        ),
    ]
