# Generated by Django 2.2.7 on 2020-01-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200116_1423'),
        ('examschedule', '0022_auto_20200125_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=100, null=True)),
                ('exam_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examtype_class', to='main_app.Classes')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_type', to='main_app.Institute')),
            ],
        ),
    ]
