# Generated by Django 2.2.7 on 2020-01-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0023_examtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTypeBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='examtype',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examtype_institute', to='main_app.Institute'),
        ),
        migrations.DeleteModel(
            name='examschedule',
        ),
        migrations.AddField(
            model_name='examtypebasicinfo',
            name='examtype_basicinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examtypebasicinfo_institute', to='examschedule.ExamType'),
        ),
    ]
