# Generated by Django 2.2.7 on 2020-01-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0024_auto_20200125_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_subject', models.CharField(max_length=100, null=True)),
                ('exam_subject_teacher', models.CharField(max_length=100, null=True)),
                ('exam_assign_teacher', models.CharField(max_length=100, null=True)),
                ('exam_date', models.DateField(auto_now=True, null=True)),
                ('exam_start_time', models.DateField(auto_now=True, null=True)),
                ('exam_end_time', models.TimeField(auto_now=True, null=True)),
            ],
        ),
    ]
