# Generated by Django 2.2.7 on 2020-01-27 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0027_auto_20200127_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_assign_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assign_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='exam_subject_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
