# Generated by Django 2.2.7 on 2020-01-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0028_auto_20200127_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_end_time',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='exam_start_time',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
