# Generated by Django 2.2.7 on 2020-01-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_subjects_subject_teacher'),
        ('examschedule', '0029_auto_20200128_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='exam_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examdetails_class', to='main_app.Classes'),
        ),
        migrations.AddField(
            model_name='examdetails',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examdetails_institute', to='main_app.Institute'),
        ),
    ]
