# Generated by Django 2.2.7 on 2020-01-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0030_auto_20200128_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_start_time',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
