# Generated by Django 2.2.7 on 2020-01-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0031_auto_20200128_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
