# Generated by Django 2.2.7 on 2020-01-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0032_auto_20200128_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdetails',
            name='exam_basic_info',
        ),
    ]
