# Generated by Django 2.2.7 on 2020-01-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0033_remove_examdetails_exam_basic_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_basic_info', to='examschedule.ExamTypeBasicInfo'),
        ),
    ]
