# Generated by Django 2.2.7 on 2020-01-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0034_examdetails_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
