# Generated by Django 2.2.7 on 2020-01-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0035_auto_20200129_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_subject_teacher',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
