# Generated by Django 2.2.7 on 2020-01-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0038_auto_20200129_1629'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examdetails',
            unique_together={('exam_subject', 'exam_subject_teacher')},
        ),
    ]
