# Generated by Django 2.2.7 on 2020-01-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examschedule', '0039_auto_20200129_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='exam_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_type_info', to='examschedule.ExamType'),
        ),
        migrations.AlterUniqueTogether(
            name='examdetails',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='ExamTypeBasicInfo',
        ),
    ]
