# Generated by Django 3.0.4 on 2020-04-20 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_code', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=7, null=True)),
                ('active', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('amount_including_tax', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_fees_tags', to='main_app.Institute')),
            ],
            options={
                'unique_together': {('institute', 'fees_code')},
            },
        ),
        migrations.CreateModel(
            name='Students_fees_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(null=True)),
                ('invoice_number', models.CharField(max_length=20, null=True)),
                ('total_due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studnts_fees_info', to='main_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Tags_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_tags', to='main_app.UserProfile')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Classes')),
                ('tags', models.ManyToManyField(related_name='tags_to_student', to='fees.School_tags')),
            ],
        ),
        migrations.CreateModel(
            name='Fees_tag_update_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('old_values', models.TextField(null=True)),
                ('new_values', models.TextField(null=True)),
                ('fees_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_updates', to='fees.School_tags')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_tag_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fees_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('due_date', models.DateField()),
                ('processing_date', models.DateField()),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institute_schedule', to='main_app.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Account_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=25)),
                ('merchant_key', models.CharField(max_length=25)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institute_account_details', to='main_app.Institute')),
            ],
            options={
                'unique_together': {('institute', 'fees_code')},
            },
        ),
        migrations.CreateModel(
            name='Students_Fees_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=40)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Tags_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_tags', to='main_app.UserProfile')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Classes')),
                ('tags', models.ManyToManyField(related_name='tags_to_student', to='fees.School_tags')),
            ],
        ),
        migrations.CreateModel(
            name='Fees_tag_update_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('old_values', models.TextField(null=True)),
                ('new_values', models.TextField(null=True)),
                ('fees_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_updates', to='fees.School_tags')),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_tag_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Tag_Processed_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField(null=True)),
                ('process_date', models.DateField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('fees_code', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=7, null=True)),
                ('active', models.CharField(max_length=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('amount_including_tax', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Tags_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_tags', to='main_app.UserProfile')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Classes')),
                ('tags', models.ManyToManyField(related_name='tags_to_student', to='fees.School_tags')),
            ],
        ),
        migrations.CreateModel(
            name='Students_fees_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(null=True)),
                ('invoice_number', models.CharField(max_length=20, null=True)),
                ('total_due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studnts_fees_info', to='main_app.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='fees_tag_update_history',
            name='fees_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_updates', to='fees.School_tags'),
        ),
        migrations.CreateModel(
            name='Account_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=25)),
                ('merchant_key', models.CharField(max_length=25)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institute_account_details', to='main_app.Institute')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='student_tag_processed_record',
            unique_together={('institute', 'process_date', 'student', 'fees_code')},
        ),
        migrations.AlterUniqueTogether(
            name='school_tags',
            unique_together={('institute', 'fees_code')},
        ),
    ]
