# Generated by Django 2.1.7 on 2020-04-02 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_auto_20200317_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees_tag_update_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='School_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_code', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=7, null=True)),
                ('active', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_fees_tags', to='main_app.Institute')),
            ],
        ),
        migrations.AddField(
            model_name='fees_tag_update_history',
            name='fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_updates', to='fees.School_tags'),
        ),
        migrations.AddField(
            model_name='fees_tag_update_history',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_tag_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='school_tags',
            unique_together={('institute', 'fees_code')},
        ),
    ]
