# Generated by Django 2.1.7 on 2020-04-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='students_fees_table',
            unique_together={('institute', 'due_date', 'student')},
        ),
    ]
