# Generated by Django 2.1.7 on 2020-04-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees_tag_update_history',
            old_name='fees',
            new_name='fees_tag',
        ),
    ]
