# Generated by Django 2.1.7 on 2020-06-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='amount_including_tax',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
