# Generated by Django 2.1.7 on 2020-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_tags',
            name='active',
            field=models.CharField(choices=[('', '-- select one --'), ('yes', 'yes'), ('no', 'no')], default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='school_tags',
            name='type',
            field=models.CharField(choices=[('', '-- select one --'), ('debit', 'debit'), ('credit', 'credit')], default='', max_length=7, null=True),
        ),
    ]
