# Generated by Django 2.1.7 on 2020-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_fees_table',
            name='invoice_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
