# Generated by Django 2.1.7 on 2020-04-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_fees_table',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studnts_fees_info', to='main_app.UserProfile'),
        ),
    ]
