# Generated by Django 2.1.7 on 2020-06-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('fees', '0002_auto_20200605_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('gateway_name', models.CharField(max_length=20, null=True)),
                ('txnid', models.CharField(max_length=90, null=True)),
                ('BANKTXNID', models.CharField(max_length=90, null=True)),
                ('TXNAMOUNT', models.CharField(max_length=12, null=True)),
                ('STATUS', models.CharField(max_length=25, null=True)),
                ('RESPCODE', models.CharField(max_length=15, null=True)),
                ('RESPMSG', models.TextField(null=True)),
                ('TXNDATE', models.DateTimeField(null=True)),
                ('BANKNAME', models.TextField(null=True)),
                ('PAYMENTMODE', models.CharField(max_length=20, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_all_transactions', to='main_app.UserProfile')),
            ],
        ),
    ]
