# Generated by Django 2.1.7 on 2020-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20200430_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_fees_table',
            name='payment_method',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
