# Generated by Django 2.1.7 on 2020-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20200424_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_fees_table',
            name='balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='students_fees_table',
            name='total_due_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='students_fees_table',
            name='total_paid',
            field=models.FloatField(null=True),
        ),
    ]
