# Generated by Django 2.1.7 on 2020-04-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_auto_20200402_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_tag_update_history',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
