# Generated by Django 2.1.7 on 2020-04-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20200424_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='amount_including_tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='tax_percentage',
            field=models.FloatField(null=True),
        ),
    ]
