# Generated by Django 2.1.7 on 2020-04-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20200418_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_fees_table',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='students_fees_table',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='students_fees_table',
            name='invoice_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students_fees_table',
            name='total_due_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='students_fees_table',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
