# Generated by Django 2.1.7 on 2020-04-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_auto_20200402_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees_tag_update_history',
            name='changes',
        ),
        migrations.AddField(
            model_name='fees_tag_update_history',
            name='new_values',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fees_tag_update_history',
            name='old_values',
            field=models.TextField(null=True),
        ),
    ]
