# Generated by Django 2.1.7 on 2020-04-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200317_1616'),
        ('fees', '0004_auto_20200403_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('due_date', models.DateField()),
                ('processing_date', models.DateField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_schedule', to='main_app.Institute')),
            ],
        ),
    ]
