# Generated by Django 2.1.7 on 2020-04-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_auto_20200424_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_fees_table',
            name='payment_date',
            field=models.DateField(null=True),
        ),
    ]
