# Generated by Django 2.1.7 on 2020-04-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_students_fees_table_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_fees_table',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
