# Generated by Django 2.1.7 on 2020-04-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200317_1616'),
        ('fees', '0006_auto_20200403_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=25)),
                ('merchant_key', models.CharField(max_length=25)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institute_account_details', to='main_app.Institute')),
            ],
        ),
    ]
