# Generated by Django 2.1.7 on 2020-04-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200424_0922'),
        ('fees', '0007_auto_20200425_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_fees_table',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.Classes'),
        ),
    ]
