# Generated by Django 2.1.7 on 2020-04-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200317_1616'),
        ('fees', '0007_account_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Tags_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tags', to='main_app.UserProfile')),
                ('tags', models.ManyToManyField(to='fees.School_tags')),
            ],
        ),
    ]
