# Generated by Django 2.1.7 on 2020-04-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200424_0922'),
        ('fees', '0008_students_fees_table_student_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_tag_processed_record',
            unique_together={('institute', 'due_date', 'student', 'fees_code')},
        ),
    ]
