# Generated by Django 2.1.7 on 2020-04-04 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_student_tags_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tags_record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tags', to='main_app.UserProfile', unique=True),
        ),
    ]
