# Generated by Django 2.1.7 on 2020-04-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_auto_20200404_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tags_record',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_tags', to='main_app.UserProfile'),
        ),
    ]
