# Generated by Django 2.1.7 on 2020-04-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200317_1616'),
        ('fees', '0010_auto_20200404_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_tags_record',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Classes'),
        ),
    ]
