# Generated by Django 2.1.7 on 2020-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_student_tags_record_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_tags_record',
            name='tags',
            field=models.ManyToManyField(related_name='tags_to_student', to='fees.School_tags'),
        ),
    ]
