# Generated by Django 2.2.7 on 2020-04-15 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200409_1333'),
        ('fees', '0012_auto_20200409_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Tag_Processed_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('process_date', models.DateField()),
                ('due_date', models.DateField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.UserProfile')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.School_tags')),
            ],
        ),
    ]
