# Generated by Django 2.1.7 on 2020-04-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_auto_20200413_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_tag_processed_record',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='student_tag_processed_record',
            name='tags',
        ),
        migrations.AddField(
            model_name='student_tag_processed_record',
            name='notification_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student_tag_processed_record',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fees.School_tags'),
        ),
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institute'),
        ),
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='process_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student_tag_processed_record',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserProfile'),
        ),
    ]
