# Generated by Django 2.1.7 on 2020-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_auto_20200413_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_tags',
            name='amount_including_tax',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
