# Generated by Django 2.1.7 on 2020-04-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200409_1333'),
        ('fees', '0015_school_tags_amount_including_tax'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_tag_processed_record',
            unique_together={('institute', 'process_date', 'student', 'tag')},
        ),
    ]
