# Generated by Django 2.2.7 on 2019-12-20 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0002_auto_20191219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_one',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_one', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_one',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_one', to=settings.AUTH_USER_MODEL),
        ),
    ]
