# Generated by Django 2.1.7 on 2020-01-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0002_auto_20200103_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lecture_eight',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_eight', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture_five',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_five', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture_four',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_four', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_one', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture_seven',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_seven', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture_six',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_six', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture_three',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_three', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lecture_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_two', to='class_schedule.Lecture'),
        ),
    ]
