# Generated by Django 2.1.7 on 2020-01-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0003_auto_20200104_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=30),
        ),
    ]
