# Generated by Django 2.2.7 on 2019-12-20 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0003_auto_20191220_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_eight',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_eight', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_five',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_five', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_four',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_four', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_seven',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_seven', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_six',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_six', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_three',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_three', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_two',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_two', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_eight',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_eight', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_five',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_five', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_four',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_four', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_seven',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_seven', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_six',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_six', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_three',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_three', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_two',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
