# Generated by Django 2.1.7 on 2020-01-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0004_auto_20200104_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_eight',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_five',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_four',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_one',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_seven',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_six',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_three',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lecture_two',
        ),
    ]
