# Generated by Django 2.2.7 on 2019-12-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0004_auto_20191220_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_order',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
