# Generated by Django 2.1.7 on 2020-01-04 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0005_auto_20200104_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lecture_eight',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_eight', to='class_schedule.Lecture'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_five',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_five', to='class_schedule.Lecture'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_four',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_four', to='class_schedule.Lecture'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_one', to='class_schedule.Lecture'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_seven',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_seven', to='class_schedule.Lecture'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_six',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_six', to='class_schedule.Lecture'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_three',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_three', to='class_schedule.Lecture'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecture_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_two', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_eight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_eight', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_five', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_four', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_one', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_seven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_seven', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_six',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_six', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_three', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_lecture_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_lecture_two', to='main_app.Subjects'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_eight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_eight', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_five',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_five', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_four',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_four', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_seven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_seven', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_six',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_six', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_three', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
