# Generated by Django 2.2.5 on 2020-01-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0006_auto_20200104_1254'),
        ('class_schedule', '0003_auto_20200104_1418'),
    ]

    operations = [
    ]
