# Generated by Django 2.1.7 on 2020-01-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0003_auto_20200104_1418'),
        ('class_schedule', '0006_auto_20200104_1254'),
    ]

    operations = [
    ]
