# Generated by Django 2.2.5 on 2020-01-06 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0007_merge_20200106_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lecture_eight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_lecture_eight', to='class_schedule.Lecture'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject_teacher_lecture_eight',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_teacher_lecture_eight', to=settings.AUTH_USER_MODEL),
        ),
    ]
