# Generated by Django 2.2.7 on 2020-01-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0007_merge_20200107_1120'),
        ('class_schedule', '0008_auto_20200106_1236'),
    ]

    operations = [
    ]
