# Generated by Django 2.2.7 on 2020-01-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_schedule', '0009_merge_20200108_1558'),
        ('class_schedule', '0009_merge_20200108_1505'),
    ]

    operations = [
    ]
