# Generated by Django 2.1.7 on 2020-02-27 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0003_auto_20200219_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=9)),
                ('Category', models.CharField(choices=[('General', 'General'), ('sc/st', 'SC/ST'), ('OBC', 'OBC')], max_length=10)),
                ('mobile_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('Email_Id', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('Nationality', models.CharField(choices=[('Indian', 'Indian'), ('other', 'Other')], max_length=10)),
                ('Address', models.CharField(max_length=400)),
                ('District', models.CharField(max_length=200)),
                ('Pin_Code', models.IntegerField()),
                ('Student_Photo', models.ImageField(upload_to='Student_Photos')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.State')),
                ('class_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_school_class', to='main_app.Classes')),
                ('school_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_request', to='main_app.Institute')),
            ],
        ),
    ]
