# Generated by Django 2.1.7 on 2020-06-21 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_query',
            name='request_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
