# Generated by Django 3.0.8 on 2020-07-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_query',
            old_name='student_aadhar_card',
            new_name='aadhar_card_number',
        ),
    ]
