# Generated by Django 2.1.7 on 2020-02-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200219_1556'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Admission_Query',
        ),
    ]
