# Generated by Django 3.0.8 on 2020-07-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_auto_20200702_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission_query',
            old_name='aadhar_card_number',
            new_name='student_aadhar_card',
        ),
    ]
