# Generated by Django 2.1.7 on 2020-02-27 09:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_auto_20200227_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission_query',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='Category',
            field=models.CharField(choices=[('General', 'General'), ('sc/st', 'SC/ST'), ('OBC', 'OBC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='District',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='Nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='Pin_Code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.State'),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='Student_Photo',
            field=models.ImageField(null=True, upload_to='Student_Photos'),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='father_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='mobile_Number',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='admission_query',
            name='mother_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
