# Generated by Django 2.1.7 on 2020-02-27 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0003_auto_20200227_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_query',
            name='request_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
