# Generated by Django 2.1.7 on 2020-05-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200513_1544'),
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inst_notice_category', to='main_app.Institute')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notice_category', to='notices.Notification_Category'),
        ),
    ]
