# Generated by Django 2.1.7 on 2020-05-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_category',
            name='institute',
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Notification_Category',
        ),
    ]
