# Generated by Django 2.1.7 on 2020-03-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20200307_1642'),
        ('notices', '0003_auto_20200309_1003'),
    ]

    operations = [
    ]
