# Generated by Django 2.1.7 on 2020-03-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_merge_20200312_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='reference_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
