# Generated by Django 2.1.7 on 2020-05-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200513_1544'),
        ('notices', '0004_auto_20200517_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notice',
            unique_together={('reference_no', 'institute')},
        ),
    ]
