# Generated by Django 2.1.7 on 2020-03-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_notice_reference_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(blank=True, choices=[('absent', 'absent')], max_length=15, null=True),
        ),
    ]
