# Generated by Django 3.0.4 on 2020-04-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200317_1616'),
        ('notices', '0006_notice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='recipients_list',
            field=models.ManyToManyField(related_name='users_notice', to='main_app.UserProfile'),
        ),
    ]
