# Generated by Django 2.1.7 on 2020-04-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_auto_20200401_1303'),
        ('notices', '0007_auto_20200403_1718'),
    ]

    operations = [
    ]
