# Generated by Django 2.2.5 on 2020-04-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_merge_20200409_1258'),
        ('notices', '0007_auto_20200401_1419'),
    ]

    operations = [
    ]
