# Generated by Django 3.0.4 on 2020-04-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_auto_20200411_1225'),
        ('notices', '0008_merge_20200409_1258'),
    ]

    operations = [
    ]
