# Generated by Django 2.2.5 on 2020-04-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_merge_20200413_1214'),
        ('notices', '0009_merge_20200409_1640'),
    ]

    operations = [
    ]
