# Generated by Django 2.2.7 on 2019-11-22 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(default='default_profile_pic.jpg', upload_to='Institute Images')),
                ('principal', models.CharField(max_length=50)),
                ('about', models.CharField(blank=True, max_length=300, null=True)),
                ('Contact_number', models.CharField(max_length=300)),
                ('address', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Name', max_length=100)),
                ('about', models.CharField(blank=True, max_length=300, null=True)),
                ('profile_pic', models.ImageField(default='default_profile_pic.jpg', upload_to='UserProfilePictures')),
                ('mobile_number', models.PositiveIntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('facebook_link', models.URLField(null=True)),
                ('institute', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='main_app.Institute')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
