# Generated by Django 2.2.7 on 2019-12-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_stage',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Middle', 'Middle'), ('Highschool', 'Highschool')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_class', to='main_app.Classes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
