# Generated by Django 2.2.7 on 2019-11-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
