# Generated by Django 2.2.7 on 2020-07-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='blood_group',
            new_name='student_blood_group',
        ),
    ]
