# Generated by Django 2.2.7 on 2020-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking_permission_changes',
            name='old_permissions',
            field=models.ManyToManyField(blank=True, related_name='old_permissions', to='main_app.App_functions'),
        ),
        migrations.AlterField(
            model_name='tracking_permission_changes',
            name='updated_permissions',
            field=models.ManyToManyField(blank=True, related_name='new_permissions', to='main_app.App_functions'),
        ),
    ]
