# Generated by Django 2.1.7 on 2020-07-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='c_District',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='c_Pin_Code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='c_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='c_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='c_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='si_c_state', to='main_app.State'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='p_State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='si_p_state', to='main_app.State'),
        ),
        migrations.AddField(
            model_name='student_info',
            name='p_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='p_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='p_district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='p_pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='same_address',
            field=models.BooleanField(null=True),
        ),
    ]
