# Generated by Django 3.0.4 on 2020-05-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='profile_pic',
            field=models.ImageField(default='default_school_pic.jpg', null=True, upload_to='Institute Images'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_permission_changes',
            name='old_permissions',
            field=models.ManyToManyField(blank=True, related_name='old_permissions', to='main_app.App_functions'),
        ),
        migrations.AlterField(
            model_name='tracking_permission_changes',
            name='updated_permissions',
            field=models.ManyToManyField(blank=True, related_name='new_permissions', to='main_app.App_functions'),
        ),
    ]
