# Generated by Django 2.1.7 on 2020-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('dissapprove', 'Dissapprove')], default='pending', max_length=25, null=True),
        ),
    ]
