# Generated by Django 2.2.7 on 2020-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_card_number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('', '-- select one --'), ('Unreserved', 'Unreserved'), ('Sc/St', 'Sc/St'), ('OBC', 'OBC')], default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_name',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('', '-- select one --'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(choices=[('', '-- select one --'), ('Married', 'Married'), ('Unmarried', 'Unmarried')], default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_name',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
