# Generated by Django 2.1.7 on 2020-06-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Role_changes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('action_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=15)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.UserProfile')),
                ('current_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_role', to='main_app.Institute_levels')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_role_changes', to='main_app.Institute')),
                ('new_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigning_role', to='main_app.Institute_levels')),
                ('request_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_role_change', to='main_app.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_change', to='main_app.UserProfile')),
            ],
        ),
    ]
