# Generated by Django 2.2.7 on 2020-07-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='establish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
