# Generated by Django 2.1.7 on 2020-01-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking_permission_changes',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
