# Generated by Django 2.1.7 on 2020-07-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='c_District',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='c_Pin_Code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='c_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='cast_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='character_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='dob_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='domicile_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='f_aadhar_card',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='f_mobile_Number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='f_occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='f_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='f_qualification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='guardian_aadhar_card',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='guardian_applicable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='guardian_mobile_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='guardian_occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='guardian_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='guardian_qualification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='id_proof_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='last_year_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='m_aadhar_card',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='m_mobile_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='m_occupation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='m_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='m_qualification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='p_State',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='si_p_state', to='main_app.State'),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='p_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='p_district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='p_pin_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='religion',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='same_address',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='student_blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document'),
        ),
    ]
