# Generated by Django 3.0.4 on 2020-06-10 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='Institute_logo',
            field=models.ImageField(blank=True, default='default_school_pic.png', null=True, upload_to='Institute logo', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])]),
        ),
    ]
