# Generated by Django 2.2.5 on 2019-12-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('dissapprove', 'Dissapprove')], default='pending', max_length=25),
        ),
    ]
