# Generated by Django 2.2.5 on 2019-12-31 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20191230_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='classes',
            name='class_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
