# Generated by Django 2.1.7 on 2020-06-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_institute_institute_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='Institute_logo',
            new_name='institute_logo',
        ),
    ]
