# Generated by Django 2.1.7 on 2020-05-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200504_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
