# Generated by Django 2.2.7 on 2019-12-07 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191206_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_description',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_institute_role', to='main_app.UserProfile'),
        ),
    ]
