# Generated by Django 2.2.5 on 2020-04-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200421_1715'),
        ('main_app', '0002_auto_20200424_0922'),
    ]

    operations = [
    ]
