# Generated by Django 2.1.7 on 2020-01-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tracking_permission_changes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_permission_changes',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
