# Generated by Django 2.2.7 on 2020-06-29 15:20

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_role_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='establish_date',
            field=models.DateField(blank=True, null=True, validators=[main_app.models.no_future]),
        ),
    ]
