# Generated by Django 2.2.5 on 2019-12-14 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_subjects_subject_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_subject', to='main_app.Classes'),
        ),
    ]
