# Generated by Django 2.2.7 on 2019-12-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userprofile_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_stage',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Middle', 'Middle'), ('Highschool', 'Highschool')], max_length=50, null=True),
        ),
    ]
