# Generated by Django 2.2.7 on 2019-12-07 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191207_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_description',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_institute_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
