# Generated by Django 2.2.7 on 2020-06-29 15:50

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200629_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='session_start_date',
            field=models.DateField(blank=True, null=True, validators=[main_app.models.session_date]),
        ),
    ]
