# Generated by Django 2.2.7 on 2020-07-15 10:01

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200715_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='establish_date',
            field=models.DateField(blank=True, null=True, validators=[main_app.models.no_future]),
        ),
        migrations.AlterField(
            model_name='institute',
            name='session_start_date',
            field=models.DateField(blank=True, null=True, validators=[main_app.models.session_date]),
        ),
    ]
