# Generated by Django 2.1.7 on 2020-05-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200505_0815'),
        ('main_app', '0002_auto_20200501_1618'),
    ]

    operations = [
    ]
