# Generated by Django 2.2.7 on 2020-03-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200219_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='class_current_year',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_next_year',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_promotion_status',
            field=models.CharField(choices=[('Promoted', 'Promoted'), ('Not Promoted', 'Not Promoted')], max_length=30, null=True),
        ),
    ]
