# Generated by Django 2.2.5 on 2019-11-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191122_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Disapprove', 'Disapprove')], default='Pending', max_length=50),
        ),
    ]
