# Generated by Django 2.2.5 on 2020-05-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200501_1618'),
        ('main_app', '0003_auto_20200505_0815'),
    ]

    operations = [
    ]
