# Generated by Django 2.2.5 on 2019-12-14 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191214_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='subject_class',
        ),
    ]
