# Generated by Django 2.2.7 on 2020-01-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userprofile_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(blank=True, max_length=266, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='institute_levels',
            name='permissions',
            field=models.ManyToManyField(related_name='user_permissions', to='main_app.App_functions'),
        ),
    ]
