# Generated by Django 2.2.5 on 2019-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='Your Full Name ', max_length=100)),
                ('Assignee', models.CharField(default='SiteAdmin', max_length=50)),
                ('Request_date', models.DateTimeField(auto_now_add=True)),
                ('Action_date', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Disapprove', 'Disapprove')], default='Pending', max_length=50)),
            ],
        ),
    ]
