# Generated by Django 2.1.7 on 2020-06-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200629_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=10)),
                ('sub_cast', models.CharField(blank=True, max_length=50, null=True)),
                ('f_mobile_Number', models.CharField(max_length=12, null=True)),
                ('f_Email_Id', models.CharField(blank=True, max_length=50, null=True)),
                ('f_aadhar_card', models.CharField(default='', max_length=20, null=True)),
                ('f_qualification', models.CharField(max_length=20, null=True)),
                ('f_occupation', models.CharField(max_length=20, null=True)),
                ('f_photo', models.ImageField(null=True, upload_to='student_document')),
                ('m_mobile_Number', models.CharField(max_length=10, null=True)),
                ('m_Email_Id', models.CharField(blank=True, max_length=100, null=True)),
                ('m_aadhar_card', models.CharField(default='', max_length=20, null=True)),
                ('m_qualification', models.CharField(max_length=20, null=True)),
                ('m_occupation', models.CharField(max_length=20, null=True)),
                ('m_photo', models.ImageField(null=True, upload_to='student_document')),
                ('guardian_name', models.CharField(max_length=30, null=True)),
                ('guardian_mobile_Number', models.CharField(max_length=10, null=True)),
                ('guardian_Email_Id', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_aadhar_card', models.CharField(default='', max_length=20, null=True)),
                ('guardian_qualification', models.CharField(max_length=20, null=True)),
                ('guardian_occupation', models.CharField(max_length=20, null=True)),
                ('guardian_photo', models.ImageField(null=True, upload_to='student_document')),
                ('guardian_applicable', models.BooleanField(null=True)),
                ('dob_certificate', models.FileField(null=True, upload_to='student_document')),
                ('id_proof_certificate', models.FileField(null=True, upload_to='student_document')),
                ('domicile_certificate', models.FileField(null=True, upload_to='student_document')),
                ('cast_certificate', models.FileField(null=True, upload_to='student_document')),
                ('character_certificate', models.FileField(null=True, upload_to='student_document')),
                ('medical_certificate', models.FileField(null=True, upload_to='student_document')),
                ('transfer_certificate', models.FileField(null=True, upload_to='student_document')),
                ('last_year_certificate', models.FileField(null=True, upload_to='student_document')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='main_app.UserProfile')),
            ],
        ),
    ]
