# Generated by Django 2.2.7 on 2019-12-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191207_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_levels',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute_levels',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
