# Generated by Django 2.2.7 on 2020-03-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200316_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='class_current_year',
            field=models.DateField(null=True),
        ),
    ]
