# Generated by Django 2.2.5 on 2019-11-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='Username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main_app.UserProfile'),
        ),
    ]
