# Generated by Django 2.2.5 on 2019-12-14 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_subjects_subject_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='institute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject_institute', to='main_app.Institute'),
            preserve_default=False,
        ),
    ]
