# Generated by Django 2.2.7 on 2019-12-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20191209_1212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institute_levels',
            unique_together={('institute', 'level_id', 'level_name')},
        ),
    ]
