# Generated by Django 2.1.7 on 2020-08-01 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200801_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='cast_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='character_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='domicile_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='id_proof_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='last_year_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
