# Generated by Django 2.2.7 on 2020-03-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200317_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='class_current_year',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='class_next_year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
