# Generated by Django 2.2.7 on 2019-12-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191209_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institute_levels',
            options={'ordering': ['-level_id']},
        ),
    ]
