# Generated by Django 2.1.7 on 2020-08-01 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200801_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='dob_certificate',
            field=models.FileField(blank=True, null=True, upload_to='student_document', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Date of Birth Certificate'),
        ),
    ]
