# Generated by Django 2.2.5 on 2020-05-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200506_1212'),
        ('main_app', '0004_merge_20200506_1421'),
        ('main_app', '0004_merge_20200505_2322'),
    ]

    operations = [
    ]
