# Generated by Django 2.1.7 on 2020-02-06 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200206_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_levels',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institute_levels',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_levels', to='main_app.Institute'),
        ),
        migrations.AlterField(
            model_name='institute_levels',
            name='level_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
