# Generated by Django 2.2.7 on 2019-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191127_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='Contact_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='institute',
            name='about',
            field=models.CharField(blank=True, default='This is about Institute', max_length=300),
        ),
        migrations.AlterField(
            model_name='institute',
            name='principal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
