# Generated by Django 2.1.7 on 2020-04-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200317_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute_disapproved_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_disapproved_user', to='main_app.Institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disapproved_from', to='main_app.UserProfile')),
            ],
        ),
    ]
