# Generated by Django 2.2.5 on 2019-12-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191214_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='code',
        ),
    ]
