# Generated by Django 2.2.7 on 2019-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_levels',
            name='level_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='institute_levels',
            unique_together=set(),
        ),
    ]
