# Generated by Django 2.2.7 on 2019-12-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20191211_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
