# Generated by Django 2.1.7 on 2020-05-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200508_1328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('institute', 'Class', 'roll_number')},
        ),
    ]
