# Generated by Django 2.1.7 on 2020-02-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200206_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_levels',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_levels', to='main_app.Institute'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_designation', to='main_app.Institute_levels'),
        ),
    ]
