# Generated by Django 2.2.5 on 2020-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200409_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute_disapproved_user',
            name='date',
        ),
        migrations.AddField(
            model_name='institute_disapproved_user',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
