# Generated by Django 2.2.5 on 2020-05-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_20200508_2310'),
        ('main_app', '0010_auto_20200511_1133'),
    ]

    operations = [
    ]
