# Generated by Django 2.2.5 on 2020-04-09 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200409_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute_disapproved_user',
            name='created_date',
        ),
        migrations.AddField(
            model_name='institute_disapproved_user',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
