# Generated by Django 2.1.7 on 2020-05-13 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200513_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_school_pic.png', null=True, upload_to='Institute Images', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])]),
        ),
    ]
