# Generated by Django 2.1.7 on 2020-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200206_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='sessoin_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
