# Generated by Django 2.2.5 on 2020-05-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_merge_20200513_1555'),
        ('main_app', '0012_auto_20200513_1544'),
    ]

    operations = [
    ]
