# Generated by Django 2.1.7 on 2020-02-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_institute_sessoin_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='sessoin_start_date',
            new_name='session_start_date',
        ),
    ]
