# Generated by Django 2.2.7 on 2019-11-29 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20191128_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='institute',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institute', to='main_app.Institute'),
        ),
    ]
