# Generated by Django 2.2.7 on 2019-11-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_institute_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_levels',
            name='level_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
