# Generated by Django 2.2.7 on 2019-11-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20191129_0955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institute_levels',
            unique_together=set(),
        ),
    ]
