# Generated by Django 2.2.7 on 2019-11-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20191129_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_levels',
            name='leved_id',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
