# Generated by Django 2.2.7 on 2019-11-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_institute_levels_leved_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute_levels',
            name='leved_id',
        ),
    ]
