# Generated by Django 2.2.7 on 2019-11-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_remove_institute_levels_leved_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_designation', to='main_app.Institute_levels'),
        ),
    ]
