# Generated by Django 2.2.7 on 2019-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_userprofile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_levels',
            name='level_id',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
