# Generated by Django 2.2.7 on 2019-11-30 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0024_institute_levels_level_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_role_desc', to='main_app.Institute')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_desc', to='main_app.Institute_levels')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_institute_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
