# Generated by Django 2.2.5 on 2019-11-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191128_1559'),
        ('main_app', '0024_institute_levels_level_id'),
    ]

    operations = [
    ]
