# Generated by Django 2.2.5 on 2019-11-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_merge_20191130_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Dissapprove', 'Dissapprove')], default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Approvals',
        ),
    ]
