# Generated by Django 2.2.5 on 2019-12-03 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0028_auto_20191202_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institute',
            name='facebook_link',
            field=models.URLField(blank=True, default='Facebook Link', null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='website_link',
            field=models.URLField(blank=True, default='Website Link', null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
