# Generated by Django 2.2.7 on 2019-12-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_auto_20191203_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='Contact_number',
            new_name='contact_number',
        ),
    ]
