# Generated by Django 2.2.7 on 2019-12-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20191204_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='code',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='about',
            field=models.CharField(blank=True, default='This is about Institute', max_length=300),
        ),
    ]
