# Generated by Django 2.2.7 on 2019-12-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20191204_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
