# Generated by Django 2.2.7 on 2019-12-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20191204_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
