# Generated by Django 2.2.7 on 2019-12-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20191204_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
