# Generated by Django 2.2.7 on 2019-12-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_auto_20191204_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='address',
            new_name='address1',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='institute',
            name='address2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='contact_number1',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='contact_number2',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='contact_number3',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='establish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
