# Generated by Django 2.2.7 on 2019-12-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_auto_20191205_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='about',
            field=models.TextField(blank=True, default='This is about Institute', max_length=300),
        ),
        migrations.AlterField(
            model_name='institute',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
