# Generated by Django 2.2.5 on 2020-06-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_code', models.CharField(max_length=10)),
                ('point_name', models.CharField(max_length=10)),
                ('point_street_no', models.IntegerField(blank=True, null=True)),
                ('point_landmark', models.CharField(max_length=15)),
                ('point_city', models.CharField(max_length=20)),
                ('point_country', models.CharField(max_length=20)),
                ('point_institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_institute', to='main_app.Institute')),
                ('point_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.State')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=10)),
                ('bus_maker', models.CharField(max_length=15, null=True)),
                ('vehicle_type', models.CharField(max_length=15, null=True)),
                ('fuel_type', models.CharField(max_length=15, null=True)),
                ('bus_color', models.CharField(max_length=10, null=True)),
                ('bus_capacity', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=25)),
                ('bus_institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_institute', to='main_app.Institute')),
            ],
        ),
    ]
