# Generated by Django 2.1.7 on 2020-07-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='bus_management.Point')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='bus_management.RouteInfo')),
            ],
        ),
    ]
