# Generated by Django 3.0.8 on 2020-08-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routemap',
            old_name='index',
            new_name='route_index',
        ),
    ]
