# Generated by Django 3.0.8 on 2020-07-16 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routemap',
            name='institute_maproute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_maproute', to='main_app.Institute'),
        ),
    ]
