# Generated by Django 2.1.7 on 2020-07-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('bus_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_institute', to='main_app.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitute', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('institute', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transport_institute', to='main_app.Institute')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bususers',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_management.Point'),
        ),
        migrations.AddField(
            model_name='bususers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_users', to='main_app.UserProfile'),
        ),
    ]
