# Generated by Django 2.2.5 on 2020-07-04 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('bus_management', '0002_auto_20200703_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_institute', to='main_app.Institute'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='main_app.UserProfile'),
        ),
    ]
