# Generated by Django 3.0.8 on 2020-07-08 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0002_routemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemap',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='bus_management.Point'),
        ),
    ]
