# Generated by Django 3.0.8 on 2020-07-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('bus_management', '0002_routemap_institute_maproute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routemap',
            name='institute_maproute',
        ),
        migrations.AddField(
            model_name='routemap',
            name='routemap_institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routemap_institute', to='main_app.Institute'),
        ),
    ]
