# Generated by Django 2.2.5 on 2020-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0003_auto_20200704_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinfo',
            name='route_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
