# Generated by Django 2.2.5 on 2020-07-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0003_trip'),
        ('bus_management', '0003_auto_20200716_1750'),
    ]

    operations = [
    ]
