# Generated by Django 3.0.8 on 2020-07-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0003_auto_20200709_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutelocation',
            name='institute',
        ),
        migrations.DeleteModel(
            name='BusUsers',
        ),
        migrations.DeleteModel(
            name='InstituteLocation',
        ),
    ]
