# Generated by Django 2.2.5 on 2020-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0004_routeinfo_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinfo',
            name='route_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
