# Generated by Django 2.2.5 on 2020-07-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0004_merge_20200717_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinfo',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='bus_management.Bus'),
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='vehicle_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='bus_management.Driver'),
        ),
    ]
