# Generated by Django 2.2.5 on 2020-07-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0005_auto_20200705_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinfo',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='routeinfo',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
