# Generated by Django 2.2.5 on 2020-07-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('bus_management', '0006_auto_20200706_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinfo',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_institute', to='main_app.Institute'),
        ),
    ]
