# Generated by Django 2.2.5 on 2020-07-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_management', '0007_routeinfo_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
