# Generated by Django 2.2.5 on 2020-07-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200706_1125'),
        ('bus_management', '0008_auto_20200708_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitute', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('institute', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transport_institute', to='main_app.Institute')),
            ],
        ),
    ]
