# Generated by Django 2.2.7 on 2019-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='applicable',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='holiday_email',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='holiday_notification',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='holiday_sms',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='holiday_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
