# Generated by Django 2.2.7 on 2019-12-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0002_auto_20191220_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='applicable',
            field=models.CharField(choices=[(('yes', 'yes'), ('no', 'no'))], default='Yes', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_email',
            field=models.CharField(choices=[(('yes', 'yes'), ('no', 'no'))], default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_notification',
            field=models.CharField(choices=[(('yes', 'yes'), ('no', 'no'))], default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_sms',
            field=models.CharField(choices=[(('yes', 'yes'), ('no', 'no'))], default='No', max_length=10, null=True),
        ),
    ]
