# Generated by Django 2.2.7 on 2019-12-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0002_auto_20191218_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='HolidayList',
        ),
    ]
