# Generated by Django 2.2.7 on 2019-12-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0003_auto_20191224_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='applicable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_email',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_notification',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_sms',
            field=models.BooleanField(null=True),
        ),
    ]
