# Generated by Django 2.2.7 on 2019-12-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0003_auto_20191218_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_email',
            field=models.CharField(default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_notification',
            field=models.CharField(default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_sms',
            field=models.CharField(default='No', max_length=10, null=True),
        ),
    ]
