# Generated by Django 2.2.7 on 2019-12-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0004_auto_20191224_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='applicable',
            field=models.BooleanField(choices=[('True', 'yes'), ('False', 'no')], null=True),
        ),
    ]
