# Generated by Django 2.2.7 on 2019-12-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0004_auto_20191218_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='applicable',
            field=models.CharField(default='Yes', max_length=10, null=True),
        ),
    ]
