# Generated by Django 2.2.7 on 2019-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0005_auto_20191224_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='applicable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='days',
            field=models.BooleanField(null=True),
        ),
    ]
