# Generated by Django 2.2.7 on 2019-12-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0005_auto_20191218_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaylist',
            name='day',
        ),
        migrations.AddField(
            model_name='holidaylist',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
