# Generated by Django 2.2.7 on 2019-12-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0006_auto_20191224_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='applicable',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
    ]
