# Generated by Django 2.2.7 on 2019-12-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0007_auto_20191224_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='applicable',
            field=models.CharField(choices=[(False, 'No'), (True, 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_email',
            field=models.CharField(choices=[(False, 'No'), (True, 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_notification',
            field=models.CharField(choices=[(False, 'No'), (True, 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_sms',
            field=models.CharField(choices=[(False, 'No'), (True, 'Yes')], max_length=10, null=True),
        ),
    ]
