# Generated by Django 2.2.7 on 2019-12-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0008_auto_20191224_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], max_length=10, null=True),
        ),
    ]
