# Generated by Django 2.2.7 on 2019-12-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0003_auto_20191224_1056'),
        ('holidaylist', '0009_auto_20191224_1239'),
    ]

    operations = [
    ]
