# Generated by Django 2.2.5 on 2019-12-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0003_auto_20191220_1457'),
        ('holidaylist', '0010_merge_20191226_1002'),
    ]

    operations = [
    ]
