# Generated by Django 2.2.5 on 2019-12-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0011_merge_20191228_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaylist',
            name='applicable',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_email',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_notification',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='holidaylist',
            name='holiday_sms',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=10, null=True),
        ),
    ]
