# Generated by Django 2.2.7 on 2019-12-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0011_auto_20191228_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to', models.CharField(max_length=1000)),
                ('mail_subject', models.CharField(max_length=1000)),
                ('mail_content', models.CharField(max_length=1000)),
                ('mail_from', models.CharField(max_length=1000)),
                ('mail_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
