# Generated by Django 2.2.7 on 2019-12-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_classes_code'),
        ('holidaylist', '0011_auto_20191219_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaylist',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_holiday', to='main_app.Institute'),
        ),
    ]
