# Generated by Django 2.2.5 on 2019-12-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidaylist', '0014_delete_sendemail'),
        ('holidaylist', '0012_auto_20191228_1052'),
    ]

    operations = [
    ]
