# Generated by Django 2.2.7 on 2019-12-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191230_1621'),
        ('holidaylist', '0014_delete_sendemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaylist',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_institute', to='main_app.Institute'),
        ),
    ]
