# Generated by Django 2.2.5 on 2019-12-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='attendance',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='daily_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='--Select--', max_length=25),
        ),
        migrations.AddField(
            model_name='attendance',
            name='rollno',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='first_name',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='last_name',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
