# Generated by Django 2.2.7 on 2019-12-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='update_date',
        ),
    ]
