# Generated by Django 2.1.7 on 2020-01-29 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200128_1428'),
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='update_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_attendance', to='main_app.Institute'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_class', to='main_app.Classes'),
        ),
    ]
