# Generated by Django 2.1.7 on 2020-02-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Attendance_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('total_student', models.CharField(max_length=10)),
                ('total_present', models.CharField(max_length=10)),
                ('total_absent', models.CharField(max_length=10)),
                ('attendance_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_class_attendace', to='main_app.Classes')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_daily_attendace', to='main_app.Institute')),
            ],
        ),
    ]
