# Generated by Django 2.2.7 on 2019-12-30 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20191230_1621'),
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='attendance',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main_app.Classes'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institue_name', to='main_app.Institute'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='rollno',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
