# Generated by Django 2.1.7 on 2020-02-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_daily_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_attendance_status',
            name='total_leave',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
