# Generated by Django 2.2.5 on 2020-01-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_attendance_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Class',
            new_name='Class_attendance',
        ),
    ]
