# Generated by Django 2.2.7 on 2020-01-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_auto_20200106_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Class_attendance',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
