# Generated by Django 2.1.7 on 2020-02-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_daily_attendance_status_total_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_attendance_status',
            name='percentage',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
